### ISSUE TITLE
After building the application the process object is no longer available

### ISSUE THREAD

**Issue by laugmanuel** [dm-drogeriemarkt/lisa#13]
After building the package with `npm run build` and running it with `serve -s build`, the application returns a white page and the Browser console shows the following error:
```
index.js:5 Uncaught ReferenceError: process is not defined
    at Module.6 (index.js:5)
    at f ((index):1)
    at Module.1099 (ActionsDropdown.js:9)
    at f ((index):1)
    at Object.425 (lisa-notification-gfx.svg:1)
    at f ((index):1)
    at a ((index):1)
    at Array.e [as push] ((index):1)
    at main.63117b3d.chunk.js:1
```
![image](https://user-images.githubusercontent.com/5444009/73283127-ecdcb600-41f2-11ea-8323-74ab0d79719c.png)

**Comment by laugmanuel** [comment]
I found the cause for this issue. It's not actually an issue in itself.
This happens, when the `.env.production` does not define `REACT_APP_SETTINGS_FILE`.
After defining the variable, the production release works.

Do you think we should default this variable to `production`?

**Comment by kamils-iRonin** [comment]
Weird, I thought that `production` is the default value defined in `.env.production`. You can try to use [get](https://lodash.com/docs/4.17.15#get) to define default value: `get(process.env, 'REACT_APP_SETTINGS_FILE', 'production')`.

**Comment by laugmanuel** [comment]
It is. As I found out we overwrite this file prior to building the production bundle because we define our GraphQL API target there. Doing so, the previously defined variable `REACT_APP_SETTINGS_FILE` got removed resulting in this behaviour.

Using your proposed code works as well. I will go ahead and open a PR for it
